# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0rdcaygbxrsx335f492a40b9i3n1lflvaqgckpzlxqqyfa5b92pd";
    aarch64-linux = "0qrhf6hjgrhlfvmshmwrmxbbxxiliiy1090mapzgyqhscymc2mpy";
    x86_64-darwin = "04m5j45js2plm87z9m4apjxw7kws71l0s98l25v8f4glab1q7ykf";
    aarch64-darwin = "1rj5ix2dn1vxivapba2fyrvab2a2cghwcy2vkkzmvqx88kgc6hxc";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft/kraftkit/releases/download/v0.12.11/kraft_0.12.11_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft/kraftkit/releases/download/v0.12.11/kraft_0.12.11_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft/kraftkit/releases/download/v0.12.11/kraft_0.12.11_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft/kraftkit/releases/download/v0.12.11/kraft_0.12.11_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kraftkit";
  version = "0.12.11";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr "kraft" "$out/bin/kraft"
    cp -vr "kraftld" "$out/bin/kraftld"
    installManPage man/*
  '';

  system = system;

  meta = {
    description = "Build and use highly customized and ultra-lightweight unikernels";
    homepage = "https://kraftkit.sh";
    license = lib.licenses.bsd3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
