# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0n79nm6vrrbnk9kpyzym5dwicrspabkg20jbd3h6rpdm5dsnnjqh";
    aarch64-linux = "0gli1kddfbgb1d917wsplvkgnjb8ywy4pmmgxvlg1qz6qg3fb5lk";
    x86_64-darwin = "0la0ndmgcykvcb6fwxak80hnn7q4rn6zwkkzjw80d0115xnngc7r";
    aarch64-darwin = "18zqin0ih9rpmb8ir6adrwnfyslb1xh0piqdnp7lpkjgabx4qbi6";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft/kraftkit/releases/download/v0.12.6/kraft_0.12.6_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft/kraftkit/releases/download/v0.12.6/kraft_0.12.6_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft/kraftkit/releases/download/v0.12.6/kraft_0.12.6_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft/kraftkit/releases/download/v0.12.6/kraft_0.12.6_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kraftkit";
  version = "0.12.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr "kraft" "$out/bin/kraft"
    cp -vr "kraftld" "$out/bin/kraftld"
    installManPage man/*
  '';

  system = system;

  meta = {
    description = "Build and use highly customized and ultra-lightweight unikernels";
    homepage = "https://kraftkit.sh";
    license = lib.licenses.bsd3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
