# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0xrkpjvvi126xx7mbnlp04lwxw2z1qwsdhnkzdn3gxdzcfys4760";
    aarch64-linux = "0aklsrrsfm98055q31kk67ij1b1mnf2srsqq54vg56b55y7nrs3x";
    x86_64-darwin = "1902ixvykgi8mji3hkvg94a2xsnw9bajcgadk2dd7rgvkggv14f4";
    aarch64-darwin = "1c2xnqr9i29jchsfkkas7qpx097q80i0342nkf3m32p68rnjaq8l";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft/kraftkit/releases/download/v0.11.5/kraft_0.11.5_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft/kraftkit/releases/download/v0.11.5/kraft_0.11.5_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft/kraftkit/releases/download/v0.11.5/kraft_0.11.5_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft/kraftkit/releases/download/v0.11.5/kraft_0.11.5_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "kraftkit";
  version = "0.11.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr "kraft" "$out/bin/kraft"
    cp -vr "kraftld" "$out/bin/kraftld"
    installManPage man/*
  '';

  system = system;

  meta = {
    description = "Build and use highly customized and ultra-lightweight unikernels";
    homepage = "https://kraftkit.sh";
    license = lib.licenses.bsd3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
