# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "04qns8c7syzfj4hg5048d69pqvb95l4f196qbfcz3v0gy4dwpnjn";
    aarch64-linux = "0hgp93fnrlg62zw36bag42ymz0ygxpyc298dvw1g0vnm1smjqzq3";
    x86_64-darwin = "0vzd4bd9hwn2zv0ch9bsa9zgpbbxh5bff5iaqm55vxlsx1v4z2ff";
    aarch64-darwin = "0zw91djw2mfvhprcfri905pshlvzwh446jpzailg5kpd5a8kg1cd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.25/unikraft-cli_0.4.2-staging.25_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.25/unikraft-cli_0.4.2-staging.25_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.25/unikraft-cli_0.4.2-staging.25_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.25/unikraft-cli_0.4.2-staging.25_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unikraft-cli-staging";
  version = "0.4.2-staging.25";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr unikraft $out/bin/$binary
    installManPage docs/man/*
  '';

  meta = {
    description = "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds.";
    homepage = "https://unikraft.com";
    license = lib.licenses.bsd3;
    mainProgram = "unikraft";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
