# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0gsfffx4vbgp8v31chnfmc8k9pzlf4qsrz2pk3is9jnvxa38qpk3";
    aarch64-linux = "02y75jrxmk98fx42jm1b6xq41gz7c85mrd9jqpspgxyx5g3a8lli";
    x86_64-darwin = "0hggq665g3xlb8rq8skp4h5gcdrrnlqvj3wss9jb527rdq939z6a";
    aarch64-darwin = "0n6k6dxq45yqjqibf7zgbriig4ch2y89090gwsm3ndd228ivy4id";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0-staging.28/unikraft-cli_0.5.0-staging.28_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0-staging.28/unikraft-cli_0.5.0-staging.28_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0-staging.28/unikraft-cli_0.5.0-staging.28_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0-staging.28/unikraft-cli_0.5.0-staging.28_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unikraft-cli-staging";
  version = "0.5.0-staging.28";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr unikraft $out/bin/$binary
    installManPage docs/man/*
  '';

  meta = {
    description = "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds.";
    homepage = "https://unikraft.com";
    license = lib.licenses.bsd3;
    mainProgram = "unikraft";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
