# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1qx8q7qv7cmdygxyi5wxa3awj4ggzvwzvxj62y7ckvhy2i69wvcp";
    aarch64-linux = "00qg8skqy4mh1afaj5ic56i3ba4brd32pfx0h0kar8nzv078342y";
    x86_64-darwin = "1wi9h46vnnj41jxbqz2qfaffgrqc0nzz2mbvp8il7dh2dijhkhq4";
    aarch64-darwin = "03d2nj3rnrq1p17aql8lnywarh6rrjnnjf229b5kks4dlayp8scv";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.23/unikraft-cli_0.4.2-staging.23_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.23/unikraft-cli_0.4.2-staging.23_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.23/unikraft-cli_0.4.2-staging.23_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.23/unikraft-cli_0.4.2-staging.23_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unikraft-cli-staging";
  version = "0.4.2-staging.23";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr unikraft $out/bin/$binary
    installManPage docs/man/*
  '';

  meta = {
    description = "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds.";
    homepage = "https://unikraft.com";
    license = lib.licenses.bsd3;
    mainProgram = "unikraft";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
