# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1h5dl4ijfjciyprhghzx5rj6sm1af8ivxqchhsjf2ymqad2rq7gz";
    aarch64-linux = "0ychchz0665snb0z0idrp1hf71gm3y15dfcnmbl2aijypc8vxbyf";
    x86_64-darwin = "1g14mmww5laabvx7swndvy2a0f5m530q56xlcczszsmvr2lgwpc0";
    aarch64-darwin = "1dc52qjigqbjrf1dlklsn52z1scdbh9bd8mg518dj6zzji7sln9a";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.9/unikraft-cli_0.4.2-staging.9_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.9/unikraft-cli_0.4.2-staging.9_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.9/unikraft-cli_0.4.2-staging.9_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.4.2-staging.9/unikraft-cli_0.4.2-staging.9_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unikraft-cli-staging";
  version = "0.4.2-staging.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr $binary $out/bin/$binary
    installManPage docs/man/*
  '';

  meta = {
    description = "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds.";
    homepage = "https://unikraft.com";
    license = lib.licenses.bsd3;
    mainProgram = "unikraft";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
