# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "078i7aypmqpr6rk7a3r0g3vv2a9fkzr5znb1ayzdgq782fzsqxqh";
    aarch64-linux = "063cbqi8776gmzqwh0hlqs95jcxpbk722z91gic9i2cjrkrgsfyj";
    x86_64-darwin = "0g78pq889z8lg3qn520s3akcqc2h2g7wskjpjrsgcx46r2rli492";
    aarch64-darwin = "1bjmapv2b22gkbnxk83z0w2hixrakv54ya4y191ijv0m4wj3iqgd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0/unikraft-cli_0.5.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0/unikraft-cli_0.5.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0/unikraft-cli_0.5.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/unikraft-cloud/cli/releases/download/v0.5.0/unikraft-cli_0.5.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "unikraft-cli";
  version = "0.5.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr unikraft $out/bin/$binary
    installManPage docs/man/*
  '';

  meta = {
    description = "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds.";
    homepage = "https://unikraft.com";
    license = lib.licenses.bsd3;
    mainProgram = "unikraft";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
